name: Delete Security Services

on:
  workflow_dispatch:
    inputs:
      services:
        description: 'Specify the services to delete (access-analyser, guard-duty, inspector, macie, securityhub, detective, config). Use a comma to separate multiple services.'
        required: true
      aws-region:
        description: 'AWS region where the stack and stackset are deployed'
        required: true
        default: 'us-east-1'
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  delete-services:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws-region }}

      - name: Set Services from Input
        id: set-services
        run: |
          if [[ -z "${{ github.event.inputs.services }}" ]]; then
            echo "No services specified. Skipping deletion."
            echo "::set-output name=services::none"
          else
            echo "::set-output name=services::${{ github.event.inputs.services }}"
          fi

  delete-stack:
    if: contains(steps.set-services.outputs.services, 'access-analyser') || contains(steps.set-services.outputs.services, 'guard-duty') || contains(steps.set-services.outputs.services, 'inspector') || contains(steps.set-services.outputs.services, 'macie') || contains(steps.set-services.outputs.services, 'securityhub') || contains(steps.set-services.outputs.services, 'detective') || contains(steps.set-services.outputs.services, 'config')
    runs-on: ubuntu-latest
    steps:
      - name: Delete Stacks for Specified Services
        run: |
          services="${{ steps.set-services.outputs.services }}"
          IFS=',' read -ra service_list <<< "$services"
          for service in "${service_list[@]}"; do
            echo "Deleting stacks for service: $service"
            aws cloudformation delete-stack --stack-name $service --region ${{ github.event.inputs.aws-region }} --retain-resources
          done

  delete-stackset:
    if: contains(steps.set-services.outputs.services, 'access-analyser') || contains(steps.set-services.outputs.services, 'guard-duty') || contains(steps.set-services.outputs.services, 'inspector') || contains(steps.set-services.outputs.services, 'macie') || contains(steps.set-services.outputs.services, 'securityhub') || contains(steps.set-services.outputs.services, 'detective') || contains(steps.set-services.outputs.services, 'config')
    runs-on: ubuntu-latest
    needs: delete-stack
    steps:
      - name: Delete StackSets for Specified Services
        run: |
          services="${{ steps.set-services.outputs.services }}"
          IFS=',' read -ra service_list <<< "$services"
          for service in "${service_list[@]}"; do
            echo "Deleting stackset for service: $service"
            aws cloudformation delete-stack-set --stack-set-name $service --region ${{ github.event.inputs.aws-region }}
          done
